#!/usr/bin/env python3
"""Train a DyNeMo model on preprocessed TMS-EEG trials.

Expected input
--------------
A pickle containing ``{subject_id: [trial, ...]}``, where each trial is a
finite NumPy array with shape ``(time, channels)``. The default input is the
standardized, time-delay embedded and PCA-reduced dataset generated by
``osl_hmm_v005_processdata.py``.

DyNeMo is continuous: ``alpha[t, mode]`` contains mode mixing coefficients
(positive and summing to one), rather than mutually exclusive HMM states.
"""

from __future__ import annotations

import argparse
import gc
import json
import logging
import os
import pickle
import random
import sys
from pathlib import Path
from typing import Dict, List, Tuple

os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "3")

import numpy as np

# Compatibility shim for osl-dynamics 2.0.2 with NumPy >= 2.0. This must be
# defined before importing osl_dynamics (an old optional dependency uses it).
if not hasattr(np, "sctypes"):
    np.sctypes = {
        "int": [np.int8, np.int16, np.int32, np.int64],
        "uint": [np.uint8, np.uint16, np.uint32, np.uint64],
        "float": [np.float16, np.float32, np.float64],
        "complex": [np.complex64, np.complex128],
        "others": [np.bool_, np.object_, np.bytes_, np.str_, np.void],
    }

import tensorflow as tf
from osl_dynamics.data import Data
from osl_dynamics.models.dynemo import Config, Model

tf.get_logger().setLevel("ERROR")
logging.getLogger("tensorflow").setLevel(logging.ERROR)

DEFAULT_INPUT = "/mnt/uphummel/scratch/nbenlamr/osl_results/data_dict_all_pca.pkl"
DEFAULT_OUTPUT = "/mnt/uphummel/scratch/nbenlamr/osl_results/Results_DyNeMo_TMS_EEG"
DEFAULT_STORE = "/mnt/uphummel/scratch/nbenlamr/osl_dynamics/tmp_dynemo"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=Path(DEFAULT_INPUT))
    parser.add_argument("--output-dir", type=Path, default=Path(DEFAULT_OUTPUT))
    parser.add_argument("--store-dir", type=Path, default=Path(DEFAULT_STORE))
    parser.add_argument("--n-modes", type=int, default=8)
    parser.add_argument("--sequence-length", type=int, default=100)
    parser.add_argument("--rnn-units", type=int, default=64)
    parser.add_argument("--batch-size", type=int, default=24)
    parser.add_argument("--learning-rate", type=float, default=1e-3)
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--kl-epochs", type=int, default=None)
    parser.add_argument("--n-init", type=int, default=5)
    parser.add_argument("--init-epochs", type=int, default=2)
    parser.add_argument("--init-take", type=float, default=0.25)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--learn-means",
        action="store_true",
        help="Learn mode means. Leave off for standardized TDE-PCA data.",
    )
    return parser.parse_args()


def set_seeds(seed: int) -> None:
    os.environ["PYTHONHASHSEED"] = str(seed)
    random.seed(seed)
    np.random.seed(seed)
    tf.random.set_seed(seed)


def load_and_validate_trials(
    path: Path, min_length: int
) -> Tuple[List[np.ndarray], List[dict], int]:
    """Load trials, validate them and retain their subject/trial mapping."""
    with path.open("rb") as file:
        data_dict = pickle.load(file)

    if not isinstance(data_dict, dict) or not data_dict:
        raise ValueError("Input must be a non-empty {subject_id: [trials]} dictionary.")

    sequences: List[np.ndarray] = []
    index: List[dict] = []
    n_channels = None
    n_dropped = 0

    for subject_id, trials in data_dict.items():
        for trial_id, trial in enumerate(trials):
            x = np.asarray(trial, dtype=np.float32)
            if x.ndim != 2:
                raise ValueError(
                    f"Subject {subject_id}, trial {trial_id}: expected 2D, got {x.shape}."
                )
            if not np.all(np.isfinite(x)):
                raise ValueError(f"Subject {subject_id}, trial {trial_id}: NaN/Inf found.")
            if x.shape[0] < min_length:
                n_dropped += 1
                continue
            if n_channels is None:
                n_channels = x.shape[1]
            elif x.shape[1] != n_channels:
                raise ValueError(
                    f"Subject {subject_id}, trial {trial_id}: {x.shape[1]} channels, "
                    f"expected {n_channels}."
                )
            sequences.append(x)
            index.append(
                {
                    "sequence_index": len(sequences) - 1,
                    "subject_id": str(subject_id),
                    "trial_index": trial_id,
                    "n_samples": int(x.shape[0]),
                }
            )

    if not sequences:
        raise ValueError(f"No trial has at least {min_length} samples.")

    print(
        f"Loaded {len(sequences)} trials from {len(data_dict)} subjects; "
        f"dropped {n_dropped} short trials; n_channels={n_channels}."
    )
    return sequences, index, int(n_channels)


def build_config(args: argparse.Namespace, n_channels: int) -> Config:
    kl_epochs = args.kl_epochs if args.kl_epochs is not None else args.epochs // 2
    if not 1 <= kl_epochs <= args.epochs:
        raise ValueError("--kl-epochs must be between 1 and --epochs.")

    return Config(
        model_name="DyNeMo",
        n_modes=args.n_modes,
        n_channels=n_channels,
        sequence_length=args.sequence_length,
        inference_rnn="lstm",
        inference_n_layers=1,
        inference_n_units=args.rnn_units,
        inference_normalization="layer",
        model_rnn="lstm",
        model_n_layers=1,
        model_n_units=args.rnn_units,
        model_normalization="layer",
        learn_alpha_temperature=True,
        initial_alpha_temperature=1.0,
        learn_means=args.learn_means,
        learn_covariances=True,
        diagonal_covariances=False,
        covariances_epsilon=1e-6,
        do_kl_annealing=True,
        kl_annealing_curve="tanh",
        kl_annealing_sharpness=5,
        n_kl_annealing_epochs=kl_epochs,
        batch_size=args.batch_size,
        learning_rate=args.learning_rate,
        lr_decay=0.05,
        n_epochs=args.epochs,
        optimizer="adam",
        loss_calc="mean",
        multi_gpu=False,
    )


def json_ready(value):
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, np.generic):
        return value.item()
    if isinstance(value, dict):
        return {str(k): json_ready(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [json_ready(v) for v in value]
    return value


def main() -> None:
    args = parse_args()
    if args.sequence_length < 2:
        raise ValueError("--sequence-length must be at least 2.")
    if not 0 < args.init_take <= 1:
        raise ValueError("--init-take must be in (0, 1].")

    set_seeds(args.seed)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    args.store_dir.mkdir(parents=True, exist_ok=True)

    sequences, sequence_index, n_channels = load_and_validate_trials(
        args.input, min_length=args.sequence_length
    )
    data = Data(sequences, store_dir=str(args.store_dir))
    config = build_config(args, n_channels)
    model = Model(config)
    model.summary()

    print(f"Running {args.n_init} random-subset initializations...")
    init_history = model.random_subset_initialization(
        data,
        n_epochs=args.init_epochs,
        n_init=args.n_init,
        take=args.init_take,
    )

    print("Training DyNeMo on all TMS-EEG trials...")
    history = model.fit(data)
    free_energy = float(model.free_energy(data))
    print(f"Final variational free energy: {free_energy:.6f}")

    model_dir = args.output_dir / "model"
    model.save(str(model_dir))

    # One alpha array per retained input trial. Trial boundaries are preserved.
    alpha = model.get_alpha(data)
    means, covariances = model.get_means_covariances()
    with (args.output_dir / "alpha.pkl").open("wb") as file:
        pickle.dump(alpha, file)
    np.save(args.output_dir / "mode_means.npy", means)
    np.save(args.output_dir / "mode_covariances.npy", covariances)

    with (args.output_dir / "history.pkl").open("wb") as file:
        pickle.dump(
            {
                "initialization": init_history,
                "training": history,
                "free_energy": free_energy,
            },
            file,
        )

    metadata = {
        "input": str(args.input.resolve()),
        "model_dir": str(model_dir.resolve()),
        "n_subjects": len({row["subject_id"] for row in sequence_index}),
        "n_trials": len(sequence_index),
        "n_channels": n_channels,
        "free_energy": free_energy,
        "arguments": vars(args),
        "sequence_index": sequence_index,
        "alpha_note": (
            "alpha.pkl is aligned with sequence_index. DyNeMo alpha values are "
            "continuous mode mixing coefficients, not discrete state probabilities."
        ),
    }
    with (args.output_dir / "metadata.json").open("w", encoding="utf-8") as file:
        json.dump(json_ready(metadata), file, indent=2)

    data.delete_dir()
    tf.keras.backend.clear_session()
    gc.collect()
    print(f"Training complete. Results saved to {args.output_dir}")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("Interrupted.", file=sys.stderr)
        raise SystemExit(130)
